import os
import time
import pandas as pd
import matplotlib.pyplot as plt
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image
from datetime import datetime
from pathlib import Path
from termcolor import colored


def generate_report(csv_path, task_name, hosts_count, high_count, medium_count, low_count, os_count, apps_count):
    """
    Generates an executive report in PDF format based on the scan results.

    This function creates a detailed PDF report, including pie and bar charts,
    a summary of vulnerabilities, and recommendations. It uses data from a CSV and xml file
    generated by the OpenVAS scan and saves the report to a specified directory.

    Args:
        csv_path (str): Path to the CSV file containing the scan results.
        task_name (str): Name of the task for which the report is generated.
        hosts_count (int): Number of hosts that were scanned.
        high_count (int): Number of high-severity vulnerabilities found.
        medium_count (int): Number of medium-severity vulnerabilities found.
        low_count (int): Number of low-severity vulnerabilities found.
        os_count (int): Number of operating systems scanned.
        apps_count (int): Number of applications scanned.
    """
    # Timestamp for filenames
    completion_time = time.strftime("%H-%M-%S_%Y-%m-%d")

    # Paths for output files
    result_graphs_dir = "result_graphs"
    os.makedirs(result_graphs_dir, exist_ok=True)  # Create the directory if it doesn't exist

    rep_csv_path = Path(csv_path)
    out_path = os.path.join("openvas_reports", f"{task_name}_executive_report_{completion_time}.pdf")
    output_pdf_path = out_path
    pie_out = os.path.join(result_graphs_dir, f"{task_name}_piechart_{completion_time}.png")
    pie_chart_path = pie_out
    bar_out = os.path.join(result_graphs_dir, f"{task_name}_barchart_{completion_time}.png")
    bar_chart_path = bar_out

    # Load and process CSV data
    df = pd.read_csv(rep_csv_path)
    df = df.astype(str).fillna("Value not found")
    df['CVSS'] = pd.to_numeric(df['CVSS'], errors='coerce')

    # Summarise vulnerability counts
    total_vulns = high_count + medium_count + low_count
    high_vulns = high_count
    medium_vulns = medium_count
    low_vulns = low_count
    hosts_scanned = hosts_count
    apps_count = apps_count
    os_count = os_count
    top_vulns = df.sort_values(by='CVSS', ascending=False)

    # Prepare data for pie chart
    labels = ["High", "Medium", "Low"]
    colors_list = ['#d43f3a', '#fdc432', '#3eae49']
    sizes = [high_vulns, medium_vulns, low_vulns]

    bar_legend_labels = ["Systems", "Applications", "Operating Systems"]
    bar_sizes = [hosts_count, os_count, apps_count]
    bar_colors = ['#bbeeff', '#3366ff', '#77aaff']

    # Create a pie chart
    fig1, ax1 = plt.subplots(figsize=(3.5, 3.5))
    wedges, texts = ax1.pie(
        sizes,
        labels=labels,
        colors=colors_list,
        startangle=90,
        wedgeprops=dict(width=0.6, edgecolor='white'),
        textprops=dict(color="black", fontsize=10)
    )

    center_circle = plt.Circle((0, 0), 0.60, fc='white')
    fig1.gca().add_artist(center_circle)

    ax1.set_title('Vulnerabilities', fontsize=12, fontweight='bold', pad=15)
    ax1.legend(wedges, labels, title="Severity", loc="center left", bbox_to_anchor=(1, 0, 0.5, 1), fontsize=10)

    plt.axis('equal')
    plt.savefig(pie_chart_path, bbox_inches='tight', dpi=300)

    # Create and save bar chart
    fig2, ax2 = plt.subplots(figsize=(3.5, 3.5))  # Smaller size
    bars = ax2.bar(bar_legend_labels, bar_sizes, color=bar_colors, edgecolor='none')

    # Add value labels on top of each bar with formatting
    for bar in bars:
        yval = bar.get_height()
        ax2.text(bar.get_x() + bar.get_width() / 2, yval + 0.5, f'{int(yval)}',
                 ha='center', va='bottom', fontsize=10, color='black')

    # Add labels and format them
    ax2.set_ylabel('Count', fontsize=10)
    ax2.set_title('Scan Information', fontsize=12, fontweight='bold', pad=15)

    ax2.tick_params(axis='x', labelsize=10)
    ax2.tick_params(axis='y', labelsize=10)
    ax2.spines['top'].set_visible(False)
    ax2.spines['right'].set_visible(False)
    ax2.spines['left'].set_linewidth(1.5)
    ax2.spines['bottom'].set_linewidth(1.5)

    # Removes x-axis label.
    ax2.set_xticklabels([])

    ax2.yaxis.grid(False)
    ax2.xaxis.grid(False)
    ax2.set_axisbelow(True)

    ax2.legend(bars, bar_legend_labels, title="Categories", loc="upper left", fontsize=8, title_fontsize=10)

    plt.tight_layout()

    # Save the bar chart
    plt.savefig(bar_chart_path, bbox_inches='tight', dpi=300)

    # Initialize PDF
    doc = SimpleDocTemplate(output_pdf_path, pagesize=A4, rightMargin=50, leftMargin=50, topMargin=50,
                            bottomMargin=50)
    elements = []

    # Styles for the PDF
    styles = getSampleStyleSheet()
    styleN = styles["BodyText"]
    styleH = styles["Heading1"]
    styleTitle = styles["Title"]
    styleH.fontSize = 15
    styleH.leading = 17

    # Title Page
    elements.append(Paragraph("Executive Vulnerability Report", styleTitle))
    elements.append(Spacer(1, 0.25 * inch))
    elements.append(
        Paragraph("This report contains sensitive information. Unauthorized distribution is prohibited.",
                  styleN))
    elements.append(Spacer(1, 0.25 * inch))
    elements.append(Paragraph(f"Created by: Greenbone Vulnerability Manager", styleN))
    elements.append(Paragraph(f"Date: {datetime.now().strftime('%Y-%m-%d')}", styleN))
    elements.append(Spacer(1, 0.5 * inch))

    # Executive Summary
    elements.append(Paragraph("1. Executive Summary", styleH))

    if high_count >= 3:
        exec_summary = (
            f"The purpose of this vulnerability scan was to identify weaknesses within our IT infrastructure "
            f"that could be exploited by attackers, potentially leading to financial loss, regulatory penalties, "
            f"or damage to our reputation. Of the {hosts_scanned} hosts scanned, {total_vulns} vulnerabilities were found, "
            f"with {high_vulns} categorized as high, posing the most significant risk. Immediate remediation of any high vulnerabilities "
            f"identified is necessary to avoid potential business disruptions and ensure the continued trust of our customers. "
            f"The report provides detailed findings and actionable recommendations to mitigate these risks, safeguarding our operations."
        )
    elif high_count > 4:
        exec_summary = (
            f"The vulnerability scan identified several high-risk vulnerabilities within our IT infrastructure. "
            f"Out of the {hosts_scanned} hosts scanned, {total_vulns} vulnerabilities were found, with {high_vulns} being high-risk. "
            f"These should be addressed promptly to avoid potential security breaches."
            f"The report provides detailed findings and actionable recommendations to mitigate these risks, safeguarding our operations."
        )
    else:
        exec_summary = (
            f"The vulnerability scan did not identify any high-risk vulnerabilities. "
            f"Out of the {hosts_scanned} hosts scanned, {total_vulns} vulnerabilities were found, with none classified as high risk "
            f"{medium_vulns} classified as medium risk, and {low_vulns} classified as low risk. Therefore, our IT infrastructure shows "
            f"a strong security posture, though continuous monitoring and improvement are still recommended. "
        )

    elements.append(Paragraph(exec_summary, styleN))
    elements.append(Spacer(1, 0.5 * inch))

    # Key Findings
    elements.append(Paragraph("2. Key Findings", styleH))

    # Custom styles
    count_style = ParagraphStyle(
        name="count",
        alignment=1,  # Centered text
        fontSize=18,
        textColor=colors.whitesmoke,
        spaceAfter=6,
        fontName="Helvetica"  # Regular (non-bold) font
    )

    label_style = ParagraphStyle(
        name="label",
        alignment=1,  # Centered text
        fontSize=8,
        textColor=colors.whitesmoke,
        spaceBefore=0,
        fontName="Helvetica-Bold"  # Bold font for labels
    )

    # Define data for the table
    data = [
        [Paragraph(str(high_vulns), count_style), Paragraph(str(medium_vulns), count_style),
         Paragraph(str(low_vulns), count_style)],
        [Paragraph("HIGH", label_style), Paragraph("MEDIUM", label_style), Paragraph("LOW", label_style)],
    ]

    # Adjusted heights to make the table shorter
    table = Table(data, colWidths=[2.25 * inch, 2.25 * inch, 2.25 * inch], rowHeights=[0.75 * inch, 0.4 * inch])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, 0), colors.HexColor("#E74C3C")),  # Red background for High
        ('BACKGROUND', (1, 0), (1, 0), colors.HexColor("#F39C12")),  # Orange background for Medium
        ('BACKGROUND', (2, 0), (2, 0), colors.HexColor("#2ECC71")),  # Green background for Low

        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),  # White text color for counts
        ('TEXTCOLOR', (0, 1), (-1, 1), colors.whitesmoke),  # White text color for labels

        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),  # Center-align text in all cells
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),  # Middle vertical alignment

        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica'),  # Regular font for counts

        ('BACKGROUND', (0, 1), (0, 1), colors.HexColor("#2C3E50")),  # Dark background for labels
        ('BACKGROUND', (1, 1), (1, 1), colors.HexColor("#2C3E50")),  # Dark background for labels
        ('BACKGROUND', (2, 1), (2, 1), colors.HexColor("#2C3E50")),  # Dark background for labels

        ('BOX', (0, 0), (-1, -1), 0.75, colors.whitesmoke),  # Thicker border around the table
    ]))

    # Add the heading
    heading = Paragraph("Vulnerability count:", ParagraphStyle(
        name="Heading1",
        fontSize=10,
        alignment=0,  # Aligned-left
        textColor=colors.black,
        spaceAfter=12,  # Space after the heading
        fontName="Helvetica"
    ))

    elements.append(heading)
    elements.append(table)
    elements.append(Spacer(1, 0.25 * inch))
    
    # Add the pie chart and bar chart side by side
    chart_table = Table(
        [
            [
                Image(pie_chart_path, width=2.50 * inch, height=2 * inch),
                Image(bar_chart_path, width=2.50 * inch, height=2 * inch)
            ]
        ],
        colWidths=[2.875 * inch, 2.875 * inch]
    )
    chart_table.setStyle(TableStyle([
        ('LEFTPADDING', (0, 0), (-1, -1), 12),
        ('RIGHTPADDING', (0, 0), (-1, -1), 12),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
        ('TOPPADDING', (0, 0), (-1, -1), 12)
    ]))
    elements.append(chart_table)
    elements.append(Spacer(1, 0.5 * inch))

    # Top 10 Critical Vulnerabilities sorted by CVSS score (highest to lowest)
    elements.append(Paragraph("3. Top 10 Vulnerabilities", styleH))
    top_10_text = (
        "The following table details the top 10 most critical vulnerabilities identified in the scan. It is ordered from "
        "most significant risk to least significant risk, with a CVSS score of 10.0 being the highest score possible "
        "awarded to vulnerabilities that pose a major risk. Please refer to the definitions table in the appendix "
        "if any of the terms are unknown to you."
    )
    elements.append(Paragraph(top_10_text, styleN))
    vuln_data = [["Vulnerability", "CVSS", "Impact", "Remediation"]]

    # Set to track unique vulnerabilities
    unique_vulns = set()

    for i, (_, row) in enumerate(top_vulns.iterrows()):
        vuln_name = row['NVT Name']

        # Check if the vulnerability is already in the set
        if vuln_name not in unique_vulns:
            # Add it to the set if it's not already present
            unique_vulns.add(vuln_name)

            # Append the row to the table data
            vuln_data.append([
                Paragraph(str(vuln_name), styleN),  # Wrap text in the 'Vulnerability' column
                Paragraph(str(row['CVSS']), styleN),  # CVSS score as a string
                Paragraph(str(row['Impact']), styleN),  # Convert to string and wrap text in the 'Impact' column
                Paragraph(str(row['Solution']), styleN)  # Convert to string and wrap text in the 'Remediation' column
            ])

            # Stop if you have added 10 unique vulnerabilities
            if len(vuln_data) > 10:
                break

    vuln_table = Table(vuln_data, colWidths=[1.3 * inch, 0.5 * inch, 2.5 * inch, 2.5 * inch])
    vuln_table_style = TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#2C3E50")),  # Blue background for the header row
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),  # White text color for the header row
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),  # Left-align text for better readability
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),  # Reduced font size for better fit
        ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
        ('TOPPADDING', (0, 0), (-1, 0), 10),
        ('BOTTOMPADDING', (1, 0), (-1, -1), 8),
        ('TOPPADDING', (1, 0), (-1, -1), 8),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.black),  # Black grid lines
        ('BOX', (0, 0), (-1, -1), 0.75, colors.black),  # Thicker border around the table
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),  # Align text to the top of each cell
    ])

    # Manually alternate row background colors
    for i in range(1, len(vuln_data)):
        if i % 2 == 0:
            bg_color = colors.HexColor("#EAECEE")  # Light gray
        else:
            bg_color = colors.HexColor("#F2F3F4")
        vuln_table_style.add('BACKGROUND', (0, i), (-1, i), bg_color)

    vuln_table.setStyle(vuln_table_style)
    elements.append(vuln_table)
    elements.append(Spacer(1, 0.75 * inch))

    # Recommendations
    elements.append(Paragraph("4. Recommendations", styleH))
    recommendations = (
        "Immediately address any critical vulnerabilities, continue to perform regular security assessments, "
        "and allocate resources to strengthen the security posture of our organization."
    )
    elements.append(Paragraph(recommendations, styleN))
    elements.append(Spacer(1, 0.75 * inch))

    # Conclusion
    elements.append(Paragraph("5. Conclusion", styleH))
    conclusion = (
        "Addressing these vulnerabilities will help mitigate risks to the organization and ensure compliance with "
        "industry standards. We recommend taking immediate action on any critical vulnerabilities and implementing long-term "
        "strategies to improve our security framework."
    )
    elements.append(Paragraph(conclusion, styleN))
    elements.append(Spacer(1, 0.75 * inch))

    # Appendix: Definitions
    elements.append(Paragraph("Appendix: Definitions", styleH))
    definitions_data = [
        ["Term", "Definition"],
        [Paragraph("CVE (Common Vulnerabilities and Exposure)", styleN), Paragraph(
            "A list of publicly disclosed computer security flaws, each identified by a unique number called a CVE ID.",
            styleN)],
        [Paragraph("Severity", styleN), Paragraph(
            "The level of impact that a vulnerability could have on the organisation, categorised as High, Medium, or Low with high being the most critical, etc.",
            styleN)],
        [Paragraph("Exploit", styleN), Paragraph(
            "A piece of code or technique that takes advantage of a vulnerability to compromise a system.",
            styleN)],
        [Paragraph("Vulnerability", styleN), Paragraph(
            "A weakness in a system that can be exploited by an attacker to perform malicious actions.",
            styleN)],
        [Paragraph("Vulnerability Scan", styleN), Paragraph(
            "Automated process that identifies, evaluates, and reports potential security weaknesses in an organisation’s IT systems.",
            styleN)],
    ]

    definitions_table = Table(definitions_data, colWidths=[2.3 * inch, 4.5 * inch])
    definitions_table_style = TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#2C3E50")),  # Blue background for the header row
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),  # White text color for the header row
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),  # Left-align text
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
        ('TOPPADDING', (0, 0), (-1, 0), 10),
        ('BOTTOMPADDING', (1, 0), (-1, -1), 8),
        ('TOPPADDING', (1, 0), (-1, -1), 8),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.black),  # Black grid lines
        ('BOX', (0, 0), (-1, -1), 0.75, colors.black),  # Thicker border around the table
    ])

    # Manually alternate row background colors for definitions table
    for i in range(1, len(definitions_data)):
        if i % 2 == 0:
            bg_color = colors.HexColor("#EAECEE")  # Light gray
        else:
            bg_color = colors.HexColor("#F2F3F4")
        definitions_table_style.add('BACKGROUND', (0, i), (-1, i), bg_color)

    definitions_table.setStyle(definitions_table_style)
    elements.append(definitions_table)
    elements.append(Spacer(1, 0.75 * inch))

    # Appendix: Recommended Actions
    elements.append(
        Paragraph("Appendix: Recommended Actions to be Taken Based on Vulnerability Severity", styleH))
    actions_data = [
        ["Severity", "Description", "Recommended Actions"],
        [Paragraph("High", styleN), Paragraph(
            "Vulnerabilities that pose an immediate threat to the organisation and could lead to significant business impact if exploited.",
            styleN),
         Paragraph(
             "1. Immediate remediation within 24 hours.<br/>2. Apply security patches or mitigations.<br/>3. Increase monitoring on affected systems.<br/>4. Notify relevant stakeholders.",
             styleN)],
        [Paragraph("Medium", styleN), Paragraph(
            "Vulnerabilities that have a moderate impact and could lead to significant issues if left unaddressed.",
            styleN),
         Paragraph(
             "1. Remediate within 7 days.<br/>2. Apply available patches or mitigations.<br/>3. Monitor for signs of exploitation.",
             styleN)],
        [Paragraph("Low", styleN), Paragraph(
            "Vulnerabilities that have a minor impact and are less likely to be exploited but should still be addressed.",
            styleN),
         Paragraph(
             "1. Remediate within 30 days.<br/>2. Apply patches as part of regular maintenance.<br/>3. Monitor the situation to ensure no escalation.",
             styleN)],
    ]

    actions_table = Table(actions_data, colWidths=[1.3 * inch, 2.5 * inch, 3 * inch])
    actions_table_style = TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#2C3E50")),  # Blue background for the header row
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),  # White text color for the header row
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),  # Left-align text
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),  # Further reduced font size
        ('BOTTOMPADDING', (0, 0), (-1, 0), 10),  # Added padding
        ('TOPPADDING', (0, 0), (-1, 0), 10),  # Added padding
        ('BOTTOMPADDING', (1, 0), (-1, -1), 8),
        ('TOPPADDING', (1, 0), (-1, -1), 8),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),  # Added padding
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),  # Added padding
        ('GRID', (0, 0), (-1, -1), 0.5, colors.black),  # Black grid lines
        ('BOX', (0, 0), (-1, -1), 0.75, colors.black),  # Thicker border around the table
    ])

    # Manually alternate row background colors for actions table
    for i in range(1, len(actions_data)):
        if i % 2 == 0:
            bg_color = colors.HexColor("#EAECEE")  # Light gray
        else:
            bg_color = colors.HexColor("#F2F3F4")
        actions_table_style.add('BACKGROUND', (0, i), (-1, i), bg_color)

    actions_table.setStyle(actions_table_style)
    elements.append(actions_table)
    elements.append(Spacer(1, 0.75 * inch))  # Increased spacing

    # Appendix: Detailed Vulnerability List
    elements.append(Paragraph("Appendix: Detailed Vulnerability List", styleH))
    elements.append(Spacer(1, 0.2 * inch))  # Add a small spacer for alignment

    # Extract relevant columns
    detailed_vulns = df[['IP', 'Severity', 'Summary', 'Solution']]

    # Prepare the data for the table
    detailed_vulns_data = [["IP Address", "Severity", "Summary", "Solution"]]
    for i, row in detailed_vulns.iterrows():
        if row['Severity'] == 'Log':
            continue
        detailed_vulns_data.append([
            Paragraph(str(row['IP']), styleN),  # IP Address
            Paragraph(str(row['Severity']), styleN),  # Severity
            Paragraph(str(row['Summary']), styleN),  # Summary
            Paragraph(str(row['Solution']), styleN)  # Solution
        ])

    detailed_vulns_table = Table(detailed_vulns_data,
                                 colWidths=[1.2 * inch, 0.7 * inch, 2.3 * inch, 2.6 * inch])

    detailed_vulns_table_style = TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#2C3E50")),  # Blue background for the header row
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),  # White text color for the header row
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),  # Left-align text for better readability
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),  # Slightly reduced font size for better fit
        ('BOTTOMPADDING', (0, 0), (-1, 0), 10),  # Added padding
        ('TOPPADDING', (0, 0), (-1, 0), 10),  # Added padding
        ('BOTTOMPADDING', (1, 0), (-1, -1), 8),
        ('TOPPADDING', (1, 0), (-1, -1), 8),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),  # Added padding
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),  # Added padding
        ('GRID', (0, 0), (-1, -1), 0.5, colors.black),  # Black grid lines
        ('BOX', (0, 0), (-1, -1), 0.75, colors.black),  # Thicker border around the table
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),  # Align text to the top of each cell
    ])

    # Manually alternate row background colors
    for i in range(1, len(detailed_vulns_data)):
        if i % 2 == 0:
            bg_color = colors.HexColor("#EAECEE")  # Light gray
        else:
            bg_color = colors.HexColor("#F2F3F4")
        detailed_vulns_table_style.add('BACKGROUND', (0, i), (-1, i), bg_color)

    detailed_vulns_table.setStyle(detailed_vulns_table_style)
    elements.append(detailed_vulns_table)
    elements.append(Spacer(1, 0.75 * inch))  # Increased spacing

    # Build PDF
    doc.build(elements)

    print(
        colored("[INFO]", "cyan") +
        f" Executive report generated and saved to " +
        colored(f"{output_pdf_path}", attrs=['bold'])
    )
    print(
        colored("[SUCCESS]", "green") +
        " All scans completed. Reports generated successfully"
    )